#!/usr/bin/env python3
# coding=utf-8
from datetime import datetime
from functools import partial
from os.path import dirname, realpath, join


# CONFIG UTILS
# ----------------------------------------------------------------------------
def path(*args):
    return realpath(join(*args))


# CONFIG
# ----------------------------------------------------------------------------
DOCS = partial(path, dirname(__file__))
SOURCE = partial(DOCS, 'source')
PROJECT = partial(DOCS, '..')
OUTPUT_FILE = PROJECT('README.rst')

autogen_comment = """.. This document was procedurally generated by %s on %s"""
document_header = autogen_comment % (__file__, datetime.now().strftime('%c'))


def included_documents():
    yield text_reader(document_header)
    yield source_file_reader('readme_title.rst')
    yield source_file_reader('readme_features.rst')
    yield source_file_reader('installation.rst')
    yield source_file_reader('usage.rst')
    yield source_file_reader('readme_credits.rst')


# PRE CONFIGURED PARTIALS
# ----------------------------------------------------------------------------

def source_file_reader(file_name):
    # noinspection PyCompatibility
    yield from file_reader(SOURCE(file_name))


def destination_file_writer(lines):
    # noinspection PyCompatibility
    yield from file_writer(OUTPUT_FILE, lines)


# PROCESS PIPELINE
# ----------------------------------------------------------------------------
def file_reader(file_name):
    with open(file_name) as f:
        # noinspection PyCompatibility
        yield from f


def text_reader(text):
    # noinspection PyCompatibility
    yield from text.splitlines(True)


def concatenate(file_iterators):
    for file_iterator in file_iterators:
        # noinspection PyCompatibility
        yield from file_iterator
        yield '\n\n'


def sanitizer(lines):
    # optional text manipulation.
    for line in lines:
        yield line


def file_writer(file_name, lines):
    with open(file_name, 'w') as f:
        for line in lines:
            yield f.write(line)


def run_script(lines):
    print('Writing README.rst ', end='')
    for i, _ in enumerate(lines):
        if i % 5 == 0:
            print('.', end='')

    print(' Done!')


# RUN SCRIPT
# ----------------------------------------------------------------------------
if __name__ == '__main__':
    documents = included_documents()
    collected_documents = concatenate(documents)
    sanitized_documents = sanitizer(collected_documents)
    write_documents = destination_file_writer(sanitized_documents)

    run_script(write_documents)
