#!/usr/bin/env python3
# coding=utf-8
from datetime import datetime
from functools import partial, reduce
from os.path import dirname, realpath, join, basename


# CONFIG UTILS
# ----------------------------------------------------------------------------
def path(*args):
    return realpath(join(*args))


# CONFIG
# ----------------------------------------------------------------------------
DOCS = partial(path, dirname(__file__))
SOURCE = partial(DOCS, 'source')
PROJECT = partial(DOCS, '..')
README = 'README.rst'
OUT_FILE = PROJECT(README)

#  %A, %B %d, %Y -> Friday, December 11, 2015
comment_line = """
.. This document was procedurally generated by %s on %s
""".strip() % (__file__, datetime.now().strftime('%A, %B %d, %Y'))

roles_override = """
.. role:: mod(literal)
.. role:: data(literal)
.. role:: envvar(literal)
"""


def include_documents(_=None):
    yield read_text(comment_line)
    yield read_text(roles_override)
    yield read_source('readme_title.rst')
    yield read_source('readme_features.rst')
    yield read_source('installation.rst')
    yield read_source('usage.rst')
    yield read_source('readme_credits.rst')


# PRE CONFIGURED PARTIALS
# ----------------------------------------------------------------------------
def read_source(file_name):
    yield from read_file(SOURCE(file_name))


def write_out(lines):
    yield from write_file(OUT_FILE, lines)


# PROCESS PIPELINE
# ----------------------------------------------------------------------------
def read_file(file_name):
    yield ".. Source defined in %s\n\n" % basename(file_name)
    with open(file_name) as f:
        yield from f


def read_text(text):
    yield ".. Source defined in %s\n\n" % __file__
    yield from text.splitlines(True)


def concatenate(sources):
    for source in sources:
        yield from source
        yield '\n\n'


def sanitize_rule__code_blocks(lines):
    """Reimplement highlight directive"""
    code_block_language = 'python'  # default rst code block language

    for line in lines:

        # setup rule
        if line.startswith('.. highlight:: '):
            code_block_language = '.. highlight:: shell'.rsplit(maxsplit=1)[-1]
            continue

        if line.startswith('.. Source defined in'):
            code_block_language = 'python'

        if line.endswith('::\n'):
            yield line.replace('::', '')
            yield '\n.. code-block:: %s\n' % code_block_language
            continue

        yield line


def sanitize(lines):
    process = sanitize_rule__code_blocks,
    lines = pipeline(process, lines)
    # optional: text manipulation goes here.
    for line in lines:

        # rule: remove orphan comments
        if line.startswith(':orphan:'):
            continue

        yield line


def write_file(file_name, lines):
    with open(file_name, 'w') as f:
        for line in lines:
            yield f.write(line)


def notify(lines):
    """Print messages for start and finish; draw a simple progress bar"""

    print('Writing', README, end='')
    for i, line in enumerate(lines):
        if i % 5 is 0:
            print('.', end='')

        yield line

    print('Done!')


# SCRIPT UTILS
# ----------------------------------------------------------------------------
def pipeline(steps, initial=None):
    """Chain results from a list of functions. Inverted ``reduce``."""

    def apply(result, step):
        yield from step(result)

    yield from reduce(apply, steps, initial)


# RUN SCRIPT
# ----------------------------------------------------------------------------
if __name__ == '__main__':
    process = include_documents, concatenate, sanitize, write_out, notify
    list(pipeline(process))
